In [1]:
import pandas as pd

orders = pd.read_csv("../data/olist_orders_dataset.csv")

print(orders.shape)
orders.head()

(99441, 8)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [2]:
print(orders.shape)

(99441, 8)

In [3]:
order_items = pd.read_csv("../data/olist_order_items_dataset.csv")

print(order_items.shape)
order_items.head()

(112650, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [4]:
items_con_orders = order_items.merge(
    orders,
    on='order_id',
    how='inner'
)

print(items_con_orders.shape)
items_con_orders.head()

(112650, 14)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00

In [5]:
products = pd.read_csv("../data/olist_products_dataset.csv")
translation = pd.read_csv("../data/product_category_name_translation.csv")

print(products.shape)
print(translation.shape)

(32951, 9)
(71, 2)

In [6]:
products_traducidos = products.merge(
    translation,
    on='product_category_name',
    how='left'
)

print(products_traducidos.shape)
products_traducidos.head()

(32951, 10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [7]:
# Merge final: items + orders + products traducidos
fact = (
    order_items
    .merge(orders, on='order_id', how='inner')
    .merge(products_traducidos, on='product_id', how='left')
)

print(fact.shape)
fact.head()

(112650, 23)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,order_estimated_delivery_date,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,2017-09-29 00:00:00,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,2017-05-15 00:00:00,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,2018-02-05 00:00:00,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,2018-08-20 00:00:00,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,2017-03-17 00:00:00,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,garden_tools

In [9]:
payments = pd.read_csv("../data/olist_order_payments_dataset.csv")
print(payments.shape)

# Pagos totales por order
payments_agg = (
    payments
    .groupby('order_id', as_index=False)['payment_value']
    .sum()
)

fact = fact.merge(payments_agg, on='order_id', how='left')
print(fact.shape)

(103886, 5)
(112650, 25)

In [10]:
fact['order_delivered_customer_date'] = pd.to_datetime(fact['order_delivered_customer_date'])
fact['order_estimated_delivery_date'] = pd.to_datetime(fact['order_estimated_delivery_date'])

# Flags — equivalente a tus columnas booleanas en fact_sales
fact['is_delivered'] = fact['order_status'] == 'delivered'
fact['is_canceled'] = fact['order_status'].isin(['canceled', 'unavailable'])
fact['is_on_time'] = (
    fact['order_delivered_customer_date'] <= fact['order_estimated_delivery_date']
)

# KPIs
total_orders = fact['order_id'].nunique()
gmv = fact['price'].sum().round(2)
revenue = fact['payment_value'].sum().round(2)
total_freight = fact['freight_value'].sum().round(2)
canceled_orders = fact[fact['is_canceled']]['order_id'].nunique()
delivered_orders = fact[fact['is_delivered']]['order_id'].nunique()
on_time_orders = fact[fact['is_on_time'] == True]['order_id'].nunique()

print(f"GMV:                 {gmv}")
print(f"Revenue:             {revenue}")
print(f"Total orders:        {total_orders}")
print(f"Cancellation rate:   {(canceled_orders / total_orders * 100).round(2)}%")
print(f"On time delivery:    {(on_time_orders / delivered_orders * 100).round(2)}%")
print(f"AOV:                 {(revenue / total_orders).round(2)}")
print(f"Total freight:       {total_freight}")

KeyError: 'payment_value'

In [11]:
fact.columns.tolist()

['order_id',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'product_category_name_english',
 'payment_value_x',
 'payment_value_y',
 'is_delivered',
 'is_canceled',
 'is_on_time']

In [12]:
fact[['payment_value_x', 'payment_value_y']].head()

   payment_value_x  payment_value_y
0            72.19            72.19
1           259.83           259.83
2           216.87           216.87
3            25.78            25.78
4           218.04           218.04

In [13]:
fact = fact.drop(columns=['payment_value_x'])
fact = fact.rename(columns={'payment_value_y': 'payment_value'})

In [16]:
fact['order_delivered_customer_date'] = pd.to_datetime(fact['order_delivered_customer_date'])
fact['order_estimated_delivery_date'] = pd.to_datetime(fact['order_estimated_delivery_date'])

# Flags — equivalente a tus columnas booleanas en fact_sales
fact['is_delivered'] = fact['order_status'] == 'delivered'
fact['is_canceled'] = fact['order_status'].isin(['canceled', 'unavailable'])
fact['is_on_time'] = (
    fact['order_delivered_customer_date'] <= fact['order_estimated_delivery_date']
)

# KPIs
total_orders = fact['order_id'].nunique()
gmv = fact['price'].sum().round(2)
revenue = fact['payment_value'].sum().round(2)
total_freight = fact['freight_value'].sum().round(2)
canceled_orders = fact[fact['is_canceled']]['order_id'].nunique()
delivered_orders = fact[fact['is_delivered']]['order_id'].nunique()
on_time_orders = fact[fact['is_on_time'] == True]['order_id'].nunique()

print(f"GMV:                 {gmv}")
print(f"Revenue:             {revenue}")
print(f"Total orders:        {total_orders}")
print(f"Cancellation rate:   {round(canceled_orders / total_orders * 100, 2)}%")
print(f"On time delivery:    {round(on_time_orders / delivered_orders * 100, 2)}%")
print(f"AOV:                 {round(revenue / total_orders, 2)}")
print(f"Total freight:       {total_freight}")

GMV:                 13591643.7
Revenue:             20308134.71
Total orders:        98666
Cancellation rate:   0.47%
On time delivery:    91.89%
AOV:                 205.83
Total freight:       2251909.54